setwd("C:/Users/chanb/Box Sync/Share/BDP2-2 Horner-Johnson/scripts")
library(checkpoint)
library(knitr)
library(rmarkdown)
checkpoint("2018-04-01", use.knitr = TRUE)
knit("simulatePower.Rmd", output = "../docs/simulatePower.md")
system("pandoc --template=GitHub.html5 --self-contained ../docs/simulatePower.md -o ../docs/simulatePower.html")
